# Generated by Django 2.2.7 on 2020-05-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255)),
                ('page_name', models.CharField(max_length=255)),
                ('page_picture', models.TextField()),
                ('page_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255)),
                ('post_message', models.TextField()),
                ('post_picture', models.TextField()),
                ('post_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_message', models.TextField()),
                ('comment_from', models.CharField(max_length=255)),
                ('comment_id', models.CharField(max_length=255)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Post')),
            ],
        ),
    ]
